### ISSUE TITLE
Problem with Python framework on OSX from homebrew

### ISSUE THREAD

**Issue by pb-cdunn** [PacificBiosciences/pitchfork#383] opened 2017-03-04 17:53 UTC
```
rsync -aKx /usr/local/bin/../lib*/python2.7/pydoc* /Users/cdunn/pf/lib/python2.7/
rsync: link_stat "/usr/local/bin/../lib*/python2.7/pydoc*" failed: No such file or directory (2)
```
This is where I find pydoc:
```
<module 'pydoc' from '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pydoc.pyc'>
```

**Comment by pb-cdunn** [comment] 2017-03-04 17:54
This works for me:

    HAVE_PYTHON           = /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/bin/python

So I guess it's an issue with the symlink. Anyway, close if you want.

**Comment by pb-cdunn** [comment] 2017-03-04 19:13
Weird. I have an error with numpy:
```
  clang: numpy/core/src/dummymodule.c
  clang -shared -L/Users/cdunn/pf/lib -fPIC -I/Users/cdunn/pf/include build/temp.macosx-10.10-x86_64-2.7/numpy/core/src/dummymodule.o -Lbuild/temp.macosx-10.10-x86_64-2.7 -o build/lib.macosx-10.10-x86_64-2.7/numpy/core/_dummy.so
  Undefined symbols for architecture x86_64:
    "_Py_InitModule4_64", referenced from:
        _init_dummy in dummymodule.o
  ld: symbol(s) not found for architecture x86_64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  Undefined symbols for architecture x86_64:
    "_Py_InitModule4_64", referenced from:
        _init_dummy in dummymodule.o
  ld: symbol(s) not found for architecture x86_64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  error: Command "clang -shared -L/Users/cdunn/pf/lib -fPIC -I/Users/cdunn/pf/include build/temp.macosx-10.10-x86_64-2.7/numpy/core/src/dummymodule.o -Lbuild/temp.macosx-10.10-x86_64-2.7 -o build/lib.macosx-10.10-x86_64-2.7/numpy/core/_dummy.so" failed with exit status 1
```
I'm going to trying forking pitchfork and switching everything to PYTHONUSERBASE.

**Comment by pb-cdunn** [comment] 2017-03-04 19:47
```
$ pip install --user numpy
...
Installing collected packages: numpy
Successfully installed numpy-1.12.0
```
MJ, Why not keep things simple? We don't need pitchfork ports for Python libraries. Those can be installed recursively if we drop `--no-deps`. Python installation works fine.

If I get things working, I'll submit a PR that you can look at.

... I wish there were HAVE_BOOST.

**Comment by pb-cdunn** [comment] 2017-03-04 19:47
boost needs libbzip2, which causes this:
```
gcc -shared -Wl,-soname -Wl,libbz2.so.1.0 -o libbz2.so.1.0.6 blocksort.o huffman.o crctable.o randtable.o compress.o decompress.o bzlib.o
ld: unknown option: -soname
```

**Comment by cdunn2001** [comment] 2017-03-04 20:42
```
LDSHARED="clang -shared" AR="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar" /Users/cdunn2001/pf/bin/pip --cache-dir /Users/cdunn2001/repo/gh/pitchfork/.git/pip install --user  /Users/cdunn2001/repo/gh/pitchfork/workspace/falcon_kit
...
    clang -shared -L/Users/cdunn2001/pf/lib -fPIC -I/Users/cdunn2001/pf/include build/temp.macosx-10.10-x86_64-2.7/src/c/ext_falcon.o build/temp.macosx-10.10-x86_64-2.7/src/c/DW_banded.o build/temp.macosx-10.10-x86_64-2.7/src/c/kmer_lookup.o build/temp.macosx-10.10-x86_64-2.7/src/c/falcon.o -L/usr/local/lib -L/usr/local/opt/sqlite/lib -o build/lib.macosx-10.10-x86_64-2.7/ext_falcon.so
    Undefined symbols for architecture x86_64:
      "_Py_InitModule4_64", referenced from:
          _initext_falcon in ext_falcon.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
However, this works fine:

    /Users/cdunn2001/pf/bin/pip --cache-dir /Users/cdunn2001/repo/gh/pitchfork/.git/pip install --user  /Users/cdunn2001/repo/gh/pitchfork/workspace/falcon_kit

The problem is `LDSHARED="clang -shared`. Could you explain why you have been using that?

**Comment by cdunn2001** [comment] 2017-03-04 21:07
Next problem, in ConsensusCore:
```
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f make/Python.mk
make/Python.mk:11: *** python include not configured properly, cannot build python module!.  Stop.
```
That is because `PYTHON_INCLUDE:=/Users/cdunn2001/pf/include/python2.7`, which is wrong. But I don't see where this gets set...

**Comment by mhsieh** [comment] 2018-08-17 20:26
pitchfork is deprecated, so I will close this as wontfix.

**Closed by mhsieh** 2018-08-17 20:26 UTC
